Lock install-pipenv-action github action version.
It looks like the new 2021.11.5 is causing this error in CI:
```
ImportError: cannot import name 'InstallCommand' from 'pipenv.vendor.pip_shims.shims' (/usr/local/lib/python3.8/dist-packages/pipenv/vendor/pip_shims/shims.py)
```