Limit pandas to <2.2 because it requires sqlalchemy 2 (#497)
Fixes this error
```
>       cur = self.con.cursor()
E       AttributeError: 'Connection' object has no attribute 'cursor'
```
which is caused by pandas refusing to import sqlalchemy because it's below 2.0.0.